% calculate each SNR of coil array in time domain. Syntax:
%
%                     SNR = SNRArray(coil, sample, Bm) 
%
% Parameters:
%
%	 coil  		- structure, generated by createCoil.m
%	 sample  	- structure, generated by createSample.m
%	 Bm			- n*n cell array, generated by BmArray.m
%
% Outputs:
%
%    SNR - 1*n array, SNR of each detected signal. 
%
% Ref: 2005-ITAP-Effects of Mutual Coupling on Interference Mitigation 
%      With a Focal Plane Array 
%
% Note: reference slides- Numerical modeling ..., page 28.
% Note: reference manuscript supplementary Note 2
%
% Mengjia He, 2022.08.24

function SNR = SNRArray(coil, sample, Bm) 

num = coil.num;	Z0 = coil.Z0;	SC = coil.SC;	SM = coil.SM;
volFactor = sample.volFactor;	numVox = sample.numVox;

% gain matrix
gain = gainArray(Z0,SC,SM);

% calculate FID
fid = zeros(m,m); 
for m = 1:num
	for n = 1:num
		fid(m,n) = sum(volFactor .* Bm{m,n});
	end
end
	
% effective signal at matching output
signal = diag(diag(gain)) * diag(diag(fid));
superSignal = conj(signal) * transpose(signal);

% noise at at matching output
Z = S2Z(SC);
noise = real(Z); % resistance matrix 
superNoise = conj(gain) * noise * transpose(gain);

% SNR
SNR = zeros(1,num);
for m = 1:num

    SNR(m) = superSignal(m,m)/superNoise(m,m);
end

end